### ISSUE TITLE
Build Failure?

### ISSUE THREAD

**Issue by ALRubinger** [arquillian/arquillian.github.com#211]
When building, I'm encountering:

```
$> awestruct -d 
...
undefined method `type=' for nil:NilClass
/home/alr/business/jboss/git/arquillian/arquillian.github.com/_ext/arquillian.rb:527:in `visit'
/home/alr/business/jboss/git/arquillian/arquillian.github.com/_ext/repository.rb:161:in `block (2 levels) in execute'
/home/alr/business/jboss/git/arquillian/arquillian.github.com/_ext/repository.rb:159:in `each'
/home/alr/business/jboss/git/arquillian/arquillian.github.com/_ext/repository.rb:159:in `block in execute'
/home/alr/business/jboss/git/arquillian/arquillian.github.com/_ext/repository.rb:150:in `each'
/home/alr/business/jboss/git/arquillian/arquillian.github.com/_ext/repository.rb:150:in `execute'
/var/lib/gems/1.9.1/gems/awestruct-0.5.1/lib/awestruct/pipeline.rb:37:in `block in execute_extensions'
/var/lib/gems/1.9.1/gems/awestruct-0.5.1/lib/awestruct/pipeline.rb:36:in `each'
/var/lib/gems/1.9.1/gems/awestruct-0.5.1/lib/awestruct/pipeline.rb:36:in `execute_extensions'
/var/lib/gems/1.9.1/gems/awestruct-0.5.1/lib/awestruct/pipeline.rb:32:in `execute'
/var/lib/gems/1.9.1/gems/awestruct-0.5.1/lib/awestruct/engine.rb:229:in `execute_pipeline'
/var/lib/gems/1.9.1/gems/awestruct-0.5.1/lib/awestruct/engine.rb:64:in `run'
/var/lib/gems/1.9.1/gems/awestruct-0.5.1/lib/awestruct/cli/generate.rb:20:in `run'
/var/lib/gems/1.9.1/gems/awestruct-0.5.1/lib/awestruct/cli/invoker.rb:104:in `invoke_generate'
/var/lib/gems/1.9.1/gems/awestruct-0.5.1/lib/awestruct/cli/invoker.rb:48:in `invoke!'
/var/lib/gems/1.9.1/gems/awestruct-0.5.1/bin/awestruct:9:in `<top (required)>'
/usr/local/bin/awestruct:23:in `load'
/usr/local/bin/awestruct:23:in `<main>'
```

**Comment by bartoszmajsak** [comment]
Fixed with the new docker image.
